main:
  port: ${MAIN_PORT:8080}

logger:
  level: ${LOG_LEVEL:debug}
  pretty: ${LOG_PRETTY:false}

auth:
  salt: ${AUTH_SALT:qwrfv23trfgvbhtrj6iues4twesfgdbdnjJTDURCGVDATR&^&%}
  expiration: ${AUTH_EXPIRATION:1h}
  jwt_private_key_path: "${RSA_PRIVATE_KEY_PATH:./keys/test.key}"

datasource:
  port: ${DATASOURCE_PORT:5432}
  host: ${DATASOURCE_HOST:db_auth}
  username: ${DATASOURCE_USERNAME:postgres}
  password: ${DATASOURCE_PASSWORD:postgres}
  db_name: ${DATASOURCE_DB_NAME:auth}
  ssl_mode: ${DATASOURCE_SSL_MODE:disable}