main:
  port: "${APP_PORT:8080}"
  name: "api-gateway"

logger:
  level: "${LOG_LEVEL:info}"
  pretty: ${LOG_PRETTY:false}

gateway:
  jwt_public_key_path: "${RSA_PUBLIC_KEY_PATH:./keys/test.key.pub}"

auth:
  url: "${AUTH_URL:http://localhost:8088}"

todo:
  url: "${TODO_URL:http://localhost:8089}"
